### PR TITLE
Create more representative icon

### PR DESCRIPTION
**Pull request by hellcp**
An icon that is more representative than bee (which would work for bumblebee more :D)
nvidia-prime

[SVG](https://gist.github.com/hellcp/2d11ab07f7b21ed7a91cad86e57d6c89)

### CODE REVIEW

**Comment by hellcp** [comment]
LIke this kind of green?
nvidia-prime svg

**Comment by wildtruc** [comment]
yep.

**Comment by hellcp** [comment]
Here you go :D

**Comment by wildtruc** [comment]
Il look back to you in a few.

**Comment by wildtruc** [comment]
Done :)

**Comment by hellcp** [comment]
Thanks :D

**Pull request merged**
